version: '3.7'
services:
  le-apache:
    container_name: 'le-apache'
    image: lets-encrypt-apache:latest
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./httpd.conf:/etc/apache2/httpd.conf
      - ./html:/var/www/localhost/htdocs/
    networks:
      - docker-network
    environment: 
      - server_name=${server_name}
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: >-
            certonly --webroot --email ${email} --agree-tos --no-eff-email --webroot-path=/data/letsencrypt -d ${server_name} -d ${server_full_name}
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot/var/log/letsencrypt:/var/log/letsencrypt
      - ./html:/data/letsencrypt
    depends_on:
      - le-apache

networks:
  docker-network:
    driver: bridge
